package com.doranco;

import java.io.Serializable;
import java.util.List;

public class Article implements Serializable {
    int id;
    Fichier fichier;
    User user;
    String content;
    boolean isVisible;
    short nbReports=0; //number of reports 0 by default

    private static final String FILE_PATH_ARTICLE= "Article.ser";
    private static List idList = Utils.readIdsFromFile(FILE_PATH_ARTICLE);

    public Article(Fichier fichier, User user) {
        setId(); //autogenerated unique id
        this.fichier = fichier;
        this.user = user;
        this.content=null; //Empty content by default
        isVisible = true; //article is visible by default
        Utils.saveToFile(this);
        System.out.println("Article list " +idList);
        System.out.println("Article created is " + this);
    }

    public int getId() {
        return id;
    }

    public void setId() {
        idList = Utils.readIdsFromFile(FILE_PATH_ARTICLE);
        this.id = Function.generateId(idList);
    }

    public Fichier getFichier() {
        return fichier;
    }

    public User getUser() {
        return user;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public boolean isVisible() {
        return isVisible;
    }

    public void setVisible(boolean visible) {
        isVisible = visible;
    }

    public short getNbReports() {
        return nbReports;
    }

    public void reportPhoto() {
        this.nbReports ++;
    }

    @Override
    public String toString() {
        return "Article{" +
                "id=" + id +
                ", fichier=" + fichier +
                ", user=" + user +
                ", content='" + content + '\'' +
                ", isVisible=" + isVisible +
                ", nbReports=" + nbReports +
                '}';
    }
}
